services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-schema.sql:/docker-entrypoint-initdb.d/01-db-schema.sql
    environment:
      - POSTGRES_USER=registration-form
      - POSTGRES_PASSWORD=registration-form
  adminer:
    image: adminer
    ports:
      - 8081:8080
