<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    <UserSecretsId>20dd9ec5-2b18-4104-a776-6ff76df87160</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="DataTransfer.fs" />
    <Compile Include="DtoMapping.fs" />
    <Compile Include="DtoParsing.fs" />
    <Compile Include="EventStore.fs" />
    <Compile Include="Controllers/EventController.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.7.0" />
    <PackageReference Include="Npgsql" Version="9.0.2" />
  </ItemGroup>

</Project>
